version: '3.8'
services:
    postgres:
      image: postgres:15.2
      container_name: db_okkam
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      networks:
        - okkam-net
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes:
        - ./scripts/db_postgres/postgres-data:/var/lib/postgresql/data
        # копируем скрипт для создания и заполнения таблицы
        - ./scripts/db_postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        - ./scripts/db_postgres/init_csv:/var/lib/postgresql/csvs

    api:
      build:
        dockerfile: api.Dockerfile
      container_name: api_okkam
      env_file:
        - test.env
      restart: always
      ports:
        - '80:80'
      links:
        - "postgres:database"
        - "redis:cache"
      networks:
        - okkam-net
      depends_on:
        - postgres

    redis:
      image: redis:7.0.9-alpine
      command: redis-server --requirepass redis
      hostname: redis
      container_name: redis
      restart: unless-stopped
      volumes:
        - ./scripts/redis/redis-data:/data
      ports:
        - '6379:6379'
      networks:
        - okkam-net

networks:
  okkam-net:
